development:
  adapter: postgresql
  encoding: unicode
  database: pims_development_new
  pool: 5
  username: postgres
  password: ankita
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: pims_test
  pool: 5
  username: postgres
  password: ankita
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: pims_production
  pool: 5
  username: postgres
  password: ankita
  host: localhost